name: backend
publish_to: none

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  drift: ^2.24.0
  # it is important that drift_dev is a regular dependency here.
  drift_dev: ^2.24.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  build_runner: ^2.4.14

dependency_overrides:
  drift_dev:
    git:
      url: https://github.com/simolus3/drift.git
      ref: develop
      path: drift_dev
