name: server_package
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  backend:
    path: ../backend/
  drift: ^2.24.0
  drift_postgres: ^1.3.0
  postgres: ^3.5.0

dependency_overrides:
  drift_dev:
    git:
      url: https://github.com/simolus3/drift.git
      ref: develop
      path: drift_dev

  build_runner: ^2.4.14
