name: server_minimal
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_web_socket: ^2.0.1
  web_socket_channel: ^3.0.1
  backend:
    path: ../backend
  sync_engine_minimal:
    git:
      url: https://github.com/makedaylight/minimal_dart_sync_engine.git
      ref: 04db394
  path: ^1.9.1
  drift_postgres: ^1.3.0
  postgres: ^3.5.3

dev_dependencies:
  http: ^1.1.0
  lints: ^5.0.0
  test: ^1.24.0
